name: Bug Report
description: Create a bug report to help us fix a problem.
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        If you haven't done so already, please read the [Community feedback Guideline](https://github.com/exyleio/exyleio/tree/master/docs/guides/community-feedback) before submitting a bug report.

  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce
      description: Steps to reproduce a bug.
    validations:
      required: true
