name: Suggestion
description: Suggest your exciting idea.
labels: ["type:suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this suggestion form!
        If you haven't done so already, please read the [Community feedback Guideline](https://github.com/exyleio/exyleio/tree/master/docs/guides/community-feedback) before submitting a suggestion.

  - type: textarea
    attributes:
      label: Description
      description: A quick and simple description of you suggestion.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why?
      description: |
        Does the suggestion solve any problem?
        If so, what is the problem and how does your suggestion solve it?
        If not, why should your suggestion get accepted?
    validations:
      required: true
