name: Deploy master server

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.MASTER_SERVER_SSH_HOST }}
          username: ${{ secrets.MASTER_SERVER_SSH_USERNAME }}
          key: ${{ secrets.MASTER_SERVER_SSH_KEY }}
          script: |
            if [ ! -d "exyleio-scripts" ]; then
              git clone https://github.com/exyleio/exyleio-scripts.git
              cd exyleio-scripts/master-server
            else
              cd exyleio-scripts
              git pull
              cd master-server
            fi
            ./tool.sh restart
